Create EKS Cluster (#2)
* Copy example EKS configuration

https://developer.hashicorp.com/terraform/tutorials/kubernetes/eks
https://github.com/hashicorp/learn-terraform-provision-eks-cluster/blob/27e7dda1c011a933b2652a0067160ccd3e6194a7/main.tf

* Remove EBS stuff that I don't intend to use

* Use instance types eligible for the free tier

* Import more code from example

https://github.com/hashicorp/learn-terraform-provision-eks-cluster/blob/27e7dda1c011a933b2652a0067160ccd3e6194a7/terraform.tf
https://github.com/hashicorp/learn-terraform-provision-eks-cluster/blob/27e7dda1c011a933b2652a0067160ccd3e6194a7/variables.tf

* Set my defult region

* Use fixed cluster name

* Remove cloud requirement

This makes local runs easier

* Create a module for EKS cluster

* Reconfigure providers

* Let's deploy an example service with our cluster

https://developer.hashicorp.com/terraform/tutorials/kubernetes/kubernetes-provider?variants=kubernetes%3Aeks

* Add missing provider name

* Workaround for a provider error?

```
Error: Unsupported argument
on .terraform/modules/eks.vpc/main.tf line 35, in resource "aws_vpc" "this":
  enable_classiclink             = null # https://github.com/hashicorp/terraform/issues/31730
An argument named "enable_classiclink" is not expected here.
```

https://github.com/aws-samples/eks-workshop-v2/issues/538

* Authorize test user for console access

* Upgrade Kubernetes version

* Parameterize EKS admins

* Deploy our service and do it with a module

* Fix AWS user to Kube user mapping